[features]
seeds = false
skip-lint = false
[programs.localnet]
ribhfunding = "9Hq4ESaAL4afDsw6mrqxHKKkBqgXM6RD4t8Vb45mykXy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
